// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJzvTohWBDoRC5Ft-QuaRIfxnwvqkOj4',
    appId: '1:1045725821597:web:495bdd1e7efae6b8ee7274',
    messagingSenderId: '1045725821597',
    projectId: 'fincell-b9995',
    authDomain: 'fincell-b9995.firebaseapp.com',
    storageBucket: 'fincell-b9995.firebasestorage.app',
    measurementId: 'G-33XGQJ3FK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADqDYVYMoL6T9C-hwAjEQXjjpMr-GnB28',
    appId: '1:1045725821597:android:2c020c7022bbef7eee7274',
    messagingSenderId: '1045725821597',
    projectId: 'fincell-b9995',
    storageBucket: 'fincell-b9995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oXXGAf-CNWXh-y-AC08YSjdVfk34IVg',
    appId: '1:1045725821597:ios:e0c605789f37067aee7274',
    messagingSenderId: '1045725821597',
    projectId: 'fincell-b9995',
    storageBucket: 'fincell-b9995.firebasestorage.app',
    androidClientId: '1045725821597-3ketn6n4g5tl7l070roloh52cl1vebl6.apps.googleusercontent.com',
    iosClientId: '1045725821597-9uf5rm8v4gfemqub484dgmu5kcv959kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fincell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4oXXGAf-CNWXh-y-AC08YSjdVfk34IVg',
    appId: '1:1045725821597:ios:e0c605789f37067aee7274',
    messagingSenderId: '1045725821597',
    projectId: 'fincell-b9995',
    storageBucket: 'fincell-b9995.firebasestorage.app',
    androidClientId: '1045725821597-3ketn6n4g5tl7l070roloh52cl1vebl6.apps.googleusercontent.com',
    iosClientId: '1045725821597-9uf5rm8v4gfemqub484dgmu5kcv959kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fincell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmJzvTohWBDoRC5Ft-QuaRIfxnwvqkOj4',
    appId: '1:1045725821597:web:d90531226a182a4dee7274',
    messagingSenderId: '1045725821597',
    projectId: 'fincell-b9995',
    authDomain: 'fincell-b9995.firebaseapp.com',
    storageBucket: 'fincell-b9995.firebasestorage.app',
    measurementId: 'G-5LXM4PB4Q9',
  );
}
